# Generated by Django 5.1.1 on 2024-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=10)),
                ('account_type', models.CharField(default='customer', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
