# Generated by Django 5.1.1 on 2024-10-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
