# Generated by Django 5.1.1 on 2024-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_remove_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Hotel Manager', 'Hotel Manager'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
