# Generated by Django 5.1.1 on 2024-11-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='first_name',
        ),
    ]
